import pkg from '@prisma/client';
const { PrismaClient } = pkg;
const prisma = new PrismaClient();
import jwt from 'jsonwebtoken';
const SECRET = process.env.JWT_SECRET || 'pace-secret-2026';
function auth(req){const t=req.headers.authorization?.replace('Bearer ','');if(!t)return null;try{return jwt.verify(t,SECRET)}catch{return null}}
export async function coachRoutes(fastify){
  fastify.get('/coach/dashboard',async(req,reply)=>{const u=auth(req);if(!u)return reply.code(401).send({error:'Nao autorizado'});const coms=await prisma.comunidade.findMany({where:{criadorId:u.userId},include:{_count:{select:{membros:true}}}});const total=coms.reduce((s,c)=>s+c._count.membros,0);return{totalAlunos:total,totalGrupos:coms.length,mensalidade:Math.round(total*3.99*100)/100,grupos:coms.map(c=>({nome:c.nome,slug:c.slug,membros:c._count.membros}))}});
  fastify.get('/coach/alunos',async(req,reply)=>{const u=auth(req);if(!u)return reply.code(401).send({error:'Nao autorizado'});const m=await prisma.membroComunidade.findMany({where:{comunidade:{criadorId:u.userId}},include:{user:{select:{id:true,name:true,email:true,gender:true,city:true}}}});return m.map(x=>({id:x.user.id,nome:x.user.name,email:x.user.email,genero:x.user.gender,cidade:x.user.city,role:x.role}))});
  fastify.post('/coach/treinos',async(req,reply)=>{const u=auth(req);if(!u)return reply.code(401).send({error:'Nao autorizado'});const{nome,descricao,tipo}=req.body;const t=await prisma.treino.create({data:{titulo:nome||'Treino',descricao:descricao||'',comunidadeId:null,diaSemana:null,horario:null,periodo:tipo||'treino'}});return{success:true,treino:t}});
  fastify.post('/coach/mural',async(req,reply)=>{const u=auth(req);if(!u)return reply.code(401).send({error:'Nao autorizado'});const{texto,tipo,comunidadeId}=req.body;if(!texto)return reply.code(400).send({error:'Texto obrigatorio'});const p=await prisma.mensagemComunidade.create({data:{conteudo:texto,tipo:tipo||'aviso',userId:u.userId,comunidadeId:comunidadeId||null}});return{success:true,post:p}});
  fastify.get('/coach/mensalidade',async(req,reply)=>{const u=auth(req);if(!u)return reply.code(401).send({error:'Nao autorizado'});const coms=await prisma.comunidade.findMany({where:{criadorId:u.userId},include:{_count:{select:{membros:true}}}});const t=coms.reduce((s,c)=>s+c._count.membros,0);return{atletasAtivos:t,valorPorAtleta:3.99,mensalidade:Math.round(t*3.99*100)/100,adesao:99.00}});
  fastify.get('/athlete/treino-hoje',async(req,reply)=>{const u=auth(req);if(!u)return reply.code(401).send({error:'Nao autorizado'});const dias=['domingo','segunda','terca','quarta','quinta','sexta','sabado'];const d=dias[new Date().getDay()];const m=await prisma.membroComunidade.findMany({where:{userId:u.userId},include:{comunidade:{include:{treinos:true}}}});const tr=[];for(const x of m){for(const t of x.comunidade.treinos){if(t.diaSemana===d)tr.push({id:t.id,titulo:t.titulo,horario:t.horario,grupo:x.comunidade.nome})}}return{dia:d,treinos:tr}});
  fastify.post('/athlete/treino-concluido',async(req,reply)=>{const u=auth(req);if(!u)return reply.code(401).send({error:'Nao autorizado'});const{treinoId}=req.body;const c=await prisma.checkin.create({data:{treinoId,userId:u.userId}});return{success:true,checkin:c}});
}
