import pkg from '@prisma/client';
const { PrismaClient } = pkg;
const prisma = new PrismaClient();
const SITES=[{name:'ChronoRun',baseUrl:'https://www.chronorun.com.br',searchPath:'/resultados',enabled:true},{name:'AtletasNet',baseUrl:'https://www.atletasnet.com.br',searchPath:'/resultados',enabled:true},{name:'SportsChronos',baseUrl:'https://www.sportschrono.com.br',searchPath:'/resultados',enabled:true}];
const TARGET_RACES=[{name:'Maratona de São Paulo',city:'São Paulo',state:'SP',year:2025},{name:'Meia Maratona de São Paulo',city:'São Paulo',state:'SP',year:2025},{name:'Maratona do Rio de Janeiro',city:'Rio de Janeiro',state:'RJ',year:2025},{name:'Maratona de Salvador',city:'Salvador',state:'BA',year:2025},{name:'Maratona de Recife',city:'Recife',state:'PE',year:2025},{name:'Maratona de Fortaleza',city:'Fortaleza',state:'CE',year:2025},{name:'Maratona de Belo Horizonte',city:'Belo Horizonte',state:'MG',year:2025},{name:'Maratona de Porto Alegre',city:'Porto Alegre',state:'RS',year:2025},{name:'Maratona de Brasília',city:'Brasília',state:'DF',year:2025},{name:'Corrida de São Silvestre',city:'São Paulo',state:'SP',year:2024},{name:'Maratona Internacional de São Paulo',city:'São Paulo',state:'SP',year:2024},{name:'Meia Maratona de Aracaju',city:'Aracaju',state:'SE',year:2025},{name:'Corrida Zé do Bairro',city:'Aracaju',state:'SE',year:2025}];
function normName(n){return n.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z\s]/g,'').trim();}
function nameSim(a,b){const na=normName(a).split(' '),nb=normName(b).split(' ');if(na[0]===nb[0]&&na[na.length-1]===nb[nb.length-1])return 1;if(na[0]===nb[0])return 0.7;if(na[na.length-1]===nb[nb.length-1])return 0.6;return 0;}
async function findOrCreate(data){const{name,age,gender,city,state}=data;const candidates=await prisma.athlete.findMany({where:{gender:gender||'M'},take:1000});let best=null,bs=0;for(const c of candidates){let s=nameSim(name,c.name)*40;if(city&&c.city&&normName(city)===normName(c.city))s+=30;if(age&&c.age&&Math.abs(age-c.age)<=2)s+=20;if(s>bs){bs=s;best=c;}}if(best&&bs>=70)return{athlete:best,isNew:false};const a=await prisma.athlete.create({data:{name,age:age||0,gender:gender||'M',city:city||'',state:state||''}});return{athlete:a,isNew:true};}
function calcPace(time,dist){if(!time||!dist)return '0:00';try{const d=parseFloat(String(dist).replace('km','').replace(',','.'));const p=String(time).split(':').map(Number);let s=p.length===3?p[0]*3600+p[1]*60+p[2]:p[0]*60+p[1];const pm=Math.floor(s/d/60),ps=Math.round((s/d)%60);return pm+':'+(String(ps).padStart(2,'0'));}catch{return '0:00';}}
function parseHTML(html,source){const results=[];const tableRe=/<tr[^>]*>(.*?)<\/tr>/gis;let tm;while((tm=tableRe.exec(html))!==null){const cells=[];const cr=/<td[^>]*>(.*?)<\/td>/gi;let cm;while((cm=cr.exec(tm[1]))!==null)cells.push(cm[1].replace(/<[^>]*>/g,'').trim());if(cells.length>=4){const pos=parseInt(cells[0]);if(!isNaN(pos)&&pos>0&&pos<10000){const timeCell=cells.find(c=>/\d{1,2}:\d{2}:\d{2}/.test(c));const nameCell=cells.find(c=>c.length>3&&!/^\d+$/.test(c)&&!/\d:\d/.test(c));if(timeCell&&nameCell)results.push({overallRank:pos,name:nameCell,time:timeCell.match(/\d{1,2}:\d{2}:\d{2}/)?.[0]||timeCell,source});}}}return results;}
async function scrapeURL(url,source){try{const ctrl=new AbortController();const t=setTimeout(()=>ctrl.abort(),15000);const res=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 Chrome/120'},signal:ctrl.signal});clearTimeout(t);if(!res.ok)return[];return parseHTML(await res.text(),source);}catch(e){return[];}}
let running=false;let logs=[];
async function runScraper(targets){if(running)return{error:'Já rodando'};running=true;logs=[];const log=m=>{console.log('[Scraper]',m);logs.push({time:new Date().toISOString(),msg:m});};log('Iniciando scraper...');let ins=0,err=0;for(const t of targets){log('Buscando: '+t.name+' '+t.year);let race=await prisma.race.findFirst({where:{name:{contains:t.name.split(' ').slice(0,3).join(' '),mode:'insensitive'}}});if(!race){try{race=await prisma.race.create({data:{name:t.name+' '+t.year,city:t.city,state:t.state,date:new Date(t.year+'-01-01'),distances:'A definir',organizer:'A definir',status:'completed'}});}catch(e){log('Erro corrida: '+e.message);continue;}}for(const site of SITES){if(!site.enabled)continue;const url=site.baseUrl+site.searchPath+'?q='+encodeURIComponent(t.name+' '+t.year);const results=await scrapeURL(url,site.name);if(results.length>0){log(results.length+' resultados de '+site.name);for(const r of results.slice(0,500)){try{const{athlete}=await findOrCreate({name:r.name||'Atleta',age:r.age||0,gender:r.gender||'M',city:t.city,state:t.state});const ex=await prisma.result.findFirst({where:{raceId:race.id,athleteId:athlete.id}});if(!ex){await prisma.result.create({data:{raceId:race.id,athleteId:athlete.id,distance:r.distance||'A definir',time:r.time||'00:00:00',pace:r.pace||calcPace(r.time,r.distance),overallRank:r.overallRank||0,genderRank:0,ageGroupRank:0,ageGroup:r.ageGroup||'Geral'}});ins++;}}catch(e){err++;}}break;}}};running=false;log('Concluído! '+ins+' inseridos, '+err+' erros');return{success:true,inserted:ins,errors:err};}
export async function scraperAutoRoutes(fastify){
  fastify.get('/scraper/auto/status',async()=>{const[races,results,athletes]=await Promise.all([prisma.race.count(),prisma.result.count(),prisma.athlete.count()]);return{scraperRunning:running,lastLogs:logs.slice(-20),stats:{races,results,athletes},targetRaces:TARGET_RACES.length};});
  fastify.post('/scraper/auto/run',async(req,reply)=>{const key=req.headers['x-api-key'];if(key!==(process.env.ADMIN_API_KEY||'pace-admin-2026'))return reply.code(401).send({error:'Não autorizado'});if(running)return{error:'Já rodando'};runScraper(TARGET_RACES);return{success:true,message:'Scraper iniciado para '+TARGET_RACES.length+' corridas!',tip:'Acompanhe em GET /scraper/auto/status'};});
  fastify.post('/scraper/auto/race',async(req,reply)=>{const key=req.headers['x-api-key'];if(key!==(process.env.ADMIN_API_KEY||'pace-admin-2026'))return reply.code(401).send({error:'Não autorizado'});const{name,city,state,year}=req.body;if(!name)return reply.code(400).send({error:'Envie name'});runScraper([{name,city:city||'',state:state||'',year:year||2025}]);return{success:true,message:'Scraper iniciado para: '+name};});
  fastify.get('/scraper/auto/logs',async()=>({running,logs}));
  fastify.post('/scraper/auto/url',async(req,reply)=>{const key=req.headers['x-api-key'];if(key!==(process.env.ADMIN_API_KEY||'pace-admin-2026'))return reply.code(401).send({error:'Não autorizado'});const{url,raceId,distance}=req.body;if(!url||!raceId)return reply.code(400).send({error:'Envie url e raceId'});const race=await prisma.race.findUnique({where:{id:raceId}});if(!race)return reply.code(404).send({error:'Corrida não encontrada'});const results=await scrapeURL(url,'URL Manual');if(!results.length)return{success:false,message:'Nenhum resultado extraído',tip:'Use importação manual por CSV'};let ok=0,err=0;for(const r of results){try{const{athlete}=await findOrCreate({name:r.name,age:r.age||0,gender:r.gender||'M',city:race.city,state:race.state});await prisma.result.create({data:{raceId,athleteId:athlete.id,distance:distance||r.distance||'A definir',time:r.time||'00:00:00',pace:calcPace(r.time,distance),overallRank:r.overallRank||0,genderRank:0,ageGroupRank:0,ageGroup:'Geral'}});ok++;}catch(e){err++;}}return{success:true,found:results.length,inserted:ok,errors:err};});
}
